# Generated by Django 2.2.2 on 2019-06-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcedMovePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(max_length=4)),
                ('original_shift', models.TextField()),
                ('forced_shift', models.TextField()),
                ('date_changed', models.DateTimeField()),
            ],
        ),
    ]
