# Generated by Django 2.2.2 on 2019-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190612_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedmovepost',
            name='date_changed',
            field=models.DateField(),
        ),
    ]
