# Generated by Django 2.2.2 on 2019-06-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_forcedmovepost_ops_inits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forcedmovepost',
            old_name='date_changed',
            new_name='shift_date',
        ),
    ]
