# Generated by Django 2.2.2 on 2019-06-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190612_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_inits', models.CharField(default='', max_length=2)),
                ('original_shift', models.CharField(max_length=4)),
                ('forced_shift', models.CharField(max_length=4)),
                ('shift_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='ForcedMovePost',
        ),
        migrations.AddField(
            model_name='forced',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Period'),
        ),
    ]
